import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

import {
  SimpleLineChart
} from 'components';



export default function Home() {

  const [series, setSeries] = useState([]);
  const [logSeries, setLogSeries] = useState([]);
  const [seedNum, setSeedNum] = useState(0);

  const handleInputChange = (e) => {
    const newSeedNum = parseFloat(e.target.value);
    if (newSeedNum==0) {
      return;
    }
    setSeedNum(newSeedNum);
    const mySeries = computeSeries(newSeedNum);
    
  }

  const computeSeries = (newSeedNum) => {
    var nextNum = newSeedNum;
    var minNumber = 1;
    var maxSteps = 1000;
    const mySeries = [
      { 
        x: 0, 
        y: newSeedNum,
        ct: 1
      },
    ];
    const myLogSeries = [
      { 
        x: 0, 
        logy: Math.log10(newSeedNum),
        ct: 1
      },
    ];

    var i = 0;
    if (newSeedNum == 1 || newSeedNum == 2 ) {
      minNumber = 0;
      maxSteps = 10;
    }

    while (nextNum > minNumber && i < maxSteps) {
      i = i + 1;
      nextNum = computeNext(i, nextNum);
      mySeries.push(
        { x: i, 
          y: nextNum,
          ct: 1
        }
      );

      myLogSeries.push(
        { x: i, 
          logy: Math.log10(nextNum),
          ct: 1
        }
      );


    }

    setSeries(mySeries);
    setLogSeries(myLogSeries);
    return mySeries;
  }

  /**
   * Computes the next number (hailstone) in the sequence
   * @param {*} i 
   * @param {*} x_i 
   * @returns 
   */
  const computeNext = (i, x_i) => {

    if (x_i % 2 == 0) {
      // console.log("i:", i, "x=", x_i, " is even");
      return x_i / 2;
    }
    else {
      // console.log("i:", i, "x=", x_i, " is odd");
      return 3 * x_i + 1;
    }
  }

  return (
    <div className="flex min-h-screen flex-col items-center justify-center pt-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-4 pb-8 text-center">
        <div className="">
          <h1 className="text-6xl font-bold">
            Collatz Conjecture
          </h1>
          <p className="mt-3 text-2l">
            Also known as the <code>Ulam Conjecture</code>, <code>Kakutani Problem</code>, <code>Syracuse Problem</code> or simply <code className='rounded-md bg-gray-100 p-1 mx-1 font-mono'>3N+1</code>
          </p>
        </div>

        <div className="my-5 flex justify-center items-center">
          <p className="text-2xl pr-4">
            Pick a number:
          </p>
          <input 
            min={1}
            autoFocus 
            type="number"
            placeholder="1" 
            step="1"  
            className="rounded text-pink-500 pr-4" 
            value={seedNum} 
            onChange={(e) => handleInputChange(e)} 
            />
          {/* <input type="checkbox" class="rounded text-pink-500" /> */}
        </div>

        <SimpleLineChart 
            className="mylinechart overflow-x-auto w-full h-full flex md:justify-center items-center" 
            data={series} 
            dataKeyX="x"
            dataKeyY="y"
          />
        <p>
          Log(x)
        </p>
        <SimpleLineChart 
          className="myloglinechart overflow-x-auto w-full h-full flex md:justify-center items-center" 
          data={logSeries} 
          dataKeyX="x"
          dataKeyY="logy"
        />

        <div className="mt-6 flex max-w-4xl flex-wrap items-center justify-around sm:w-full">
          <a
            href="#"
            className="mt-6 w-96 rounded-xl border p-6 text-left hover:text-blue-600 focus:text-blue-600"
          >
            <h3 className="text-2xl font-bold">The rules &rarr;</h3>
            <p className="mt-4 text-xl">
              Take any positive integer number.   
              If the number is odd, multiply it by <code>three</code> and add <code>one</code>.
              If the number is even, divide by <code>two</code>. 
              Repeat with every new number.
            </p>
          </a>

          <a
            href="#"
            className="mt-6 w-96 rounded-xl border p-6 text-left hover:text-blue-600 focus:text-blue-600"
          >
            <h3 className="text-2xl font-bold">The conjecture &rarr;</h3>
            <p className="mt-4 text-xl">
            Every positive integer, if you apply these rules, will end up in a four, two, one loop.  
            This is commonly called the <code>Collatz Conjecture</code> after German mathematician Luther Collatz.  
            </p>
          </a>
        </div>

      </main>

      <footer className="flex h-24 w-full items-center justify-center border-t">
        <a
          className="flex items-center justify-center gap-2"
          href="https://www.webzein.gr?utm_source=code&utm_medium=default&utm_campaign=collatz-conjecture"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created with ❤️ by{' '}
          <Image src="/webzein.svg" alt="Webzein Logo" width={16} height={20} />
        </a>
      </footer>
    </div>
  )
}
